### ISSUE TITLE
Thanks for the helpful example

### ISSUE THREAD

**Issue by heymartinadams** [jonaskello/graphql-hooks-normcache-example#1]
Hi Jonas,

Thank you for taking time to write down such a helpful example. Also experimenting with `graphql-hooks` here; that’s how I came across your [issue](https://github.com/nearform/graphql-hooks/issues/334).

Copied your example into vanilla JavaScript and works wonders. Second query uses cache :)

What I don’t understand, though, is the `get`, `set`, etc. function of the normalized cache. In [your example](https://github.com/jonaskello/graphql-hooks-normcache-example/blob/master/src/norm-cache.ts#L14-L24), you obtain the query and variables from the cache `keyObject` (via `keyObject.operation.query` and `keyObject.operation.variables`), but when I print out my cache keys via `cache.keys()`, I just get an array of strings, so naturally I’m unable to perform the command `cache.get(keyObject)`.

Any thoughts?

**Comment by jonaskello** [comment]
Nice to hear that the example is helpful :-)

Since they cache is normalized the data is not stored with the queries as keys. Instead the query result tree is normalized into separate objects and the keys in the cache are object IDs (similar to primary keys in a normalized database). I think the example return those object IDs in cache.keys() which is why you get an array of strings.

If you want to work with the cache directly (outside of graphql-hooks) I think you could keep a direct reference to it. I'll se if I can amend the example to show what I mean by that.

Are you only interested in printing out the cache for debugging or is there some other scenario you want to achieve?

**Comment by jonaskello** [comment]
I added some examples how to programatically use the cache in [this commit](https://github.com/jonaskello/graphql-hooks-normcache-example/commit/b0f6532165b767411656de9771bf7e67847ba268).

It might also be helpful to read the docs for [graphql-norm](https://github.com/dividab/graphql-norm). The denormalize() function from that package is basically how you "query" the cache.

**Comment by heymartinadams** [comment]
Thank you, @jonaskello ☺️

I just wanted to better understand how the cache works (since I don’t understand Typescript very well). Re-wrote it in JavaScript, like this:

```javascript
// Packages
import { normalize, denormalize, merge } from 'graphql-norm'
import parse from 'graphql-tag'

export const normalizedData = ({ api, variables, data, getKey }) =>
  normalize(parse(api), variables, data, getKey)

const denormalizeData = ({ api, variables, cache }) => denormalize(parse(api), variables, cache)

export const normCache = getKey => {
  let cache = {}
  return {
    get(keyObject) {
      const denormalizedData = denormalizeData({
        api: keyObject.operation.query,
        variables: keyObject.operation.variables,
        cache
      })
      return (
        denormalizedData.data && {
          data: denormalizedData.data,
          error: false
        }
      )
    },
    set(keyObject, data) {
      cache = merge(
        cache,
        normalizedData({
          api: keyObject.operation.query,
          variables: keyObject.operation.variables,
          data: data.data,
          getKey
        })
      )
    },
    delete(_keyObject) {
      // Do nothing?
    },
    clear() {
      cache = {}
    },
    keys() {
      return Object.keys(cache)
    },
    getInitialState() {
      return cache
    }
  }
}
```
